# -*- coding:utf-8-*-
#+TITLE: 12 Variables
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com
#+STARTUP: overview
#+OPTIONS: num:nil
* 12 Variables
** 12.2 Variables that Never Change
   In Emacs Lisp, certain symbols normally evaluate to themselves. These include nil and t, as well as any symbol whose name starts with ‘:’ (these are called keywords). These symbols cannot be rebound, nor can their values be changed. Any attempt to set or bind nil or t signals a setting-constant error. The same is true for a keyword (a symbol whose name starts with ‘:’), if it is interned in the standard obarray, except that setting such a symbol to itself is not an error.

   在 Emacs Lisp 中，某些符号通常求值等于自身。包括 nil 和 t，以及名称以':'开头的任何符号（这些都称为 keywords）。这些符号不能再次绑定，也不能改变它们的值。任何设置或绑定 nil 或 t 的尝试都会发出设置常量错误信号。对于 keyword（名称以':'开头的符号），如果它是在标准 obarray 中 interned 的，则情况也是如此，除非将这样的符号设置为自身。

   #+BEGIN_EXAMPLE
      nil == 'nil
           ⇒ nil
      (setq nil 500)
      error--> Attempt to set constant symbol: nil
 #+END_EXAMPLE

   + Function: keywordp object

     function returns t if object is a symbol whose name starts with ‘:’, interned in the standard obarray, and returns nil otherwise.

     如果 object 是名称以':'开头的符号，在标准 obarray 中 interned，则在函数返回 t，否则返回 nil。

   These constants are fundamentally different from the constants defined using the defconst special form (see [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Variables.html#Defining-Variables][Defining Variables]] ). A defconst form serves to inform human readers that you do not intend to change the value of a variable, but Emacs does not raise an error if you actually change it.

   这些常量与使用 defconst 特殊形式定义的常量根本不同（请参阅 [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Variables.html#Defining-Variables][Defining Variables]] ）。defconst form 用于告知人类读者不打算更改变量的值，但如果实际更改了 Emacs，则不会引发错误。

   A small number of additional symbols are made read-only for various practical reasons. These include enable-multibyte-characters, most-positive-fixnum, most-negative-fixnum, and a few others. Any attempt to set or bind these also signals a setting-constant error.

   由于各种实际原因，少量符号是只读的。比如 enable-multibyte-characters，most-positive-fixnum，most-negative-fixnum 和其他一些。任何设置或绑定它们的尝试也会发出设置常量错误信号。
